apiVersion : apps/v1
kind: Deployment
metadata:
  name: k8s-spring-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-spring-project
  template:
    metadata:
      labels:
        app: k8s-spring-project
        backstage.io/kubernetes-id: K8sSpringProject
    spec:
      containers:
        - name: k8s-spring-project
          image: ktdsidpdemo.azurecr.io/{ cookiecutter.image_name }}:v1.0.0
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: acr-credentials