name: Deploy JAR from Blob to VM
description: Downloads JAR from Azure Blob Storage and deploys it to a VM via SSH.

inputs:
  environment:
    description: 'Deployment environment (dev or prd)'
    required: true
  storage-account:
    description: 'Azure Blob Storage account name'
    required: true
  storage-container:
    description: 'Azure Blob Storage container name'
    required: true
  storage-access-key:
    description: 'Azure Blob Storage access key'
    required: true
  ssh-private-key:
    description: 'SSH private key for VM access'
    required: true
  vm-ip:
    description: 'IP address of the target VM'
    required: true
  vm-user:
    description: 'Username for SSH login'
    required: true
  app-name:
    description: 'Name of the application to be deployed'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up SSH
      id: setup-ssh
      run: |
        echo "${{ inputs.ssh-private-key }}" > ssh_key.pem
        chmod 600 ssh_key.pem
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ inputs.vm-ip }} >> ~/.ssh/known_hosts
      shell: bash

    - name: Download application JAR from Azure Blob
      id: download-blob
      run: |
        az storage blob download \
          --account-name ${{ inputs.storage-account }} \
          --container-name ${{ inputs.storage-container }} \
          --name "${{ inputs.app-name }}.jar" \
          --file "${{ inputs.app-name }}.jar" \
          --auth-mode key \
          --account-key "${{ inputs.storage-access-key }}"
      shell: bash

    - name: Deploy application to VM via SSH
      id: deploy-app
      run: |
        scp -i ssh_key.pem ./${{ inputs.app-name }}.jar ${{ inputs.vm-user }}@${{ inputs.vm-ip }}:/home/${{ inputs.vm-user }}/
        ssh -i ssh_key.pem ${{ inputs.vm-user }}@${{ inputs.vm-ip }} << EOF
          # Stop existing application if running
          if pgrep -f ${{ inputs.app-name }}; then
            pkill -f ${{ inputs.app-name }}
          fi

          # Start new application
          nohup java -jar /home/${{ inputs.vm-user }}/$(basename "${{ inputs.app-name }}.jar") > /dev/null 2>&1 &
        EOF
      shell: bash