name: Deploy VM using SSH and Blob

on:
  workflow_dispatch:
    inputs:
      runner:
        required: true
        type: choice
        options:
          - ubuntu-latest
      environment:
        description: "Deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prd

jobs:
  deploy-dev:
    name: Deploy to dev VM using ssh and blob
    runs-on: "${{ inputs.runner }}"
    if: ${{ inputs.environment == 'dev' }}
    steps:
      - name: Check out the repository    # 리포지토리 체크아웃
        uses: actions/checkout@v4

      - name: Log in to Azure CLI
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          echo "$AZURE_CREDENTIALS" > azure_credentials.json
          az login \
            --service-principal \
            --username $(jq -r .clientId azure_credentials.json) \
            -p=$(jq -r .clientSecret azure_credentials.json) \
            --tenant $(jq -r .tenantId azure_credentials.json)
          az account set --subscription $(jq -r .subscriptionId azure_credentials.json)
        shell: bash

      - name: Deploy java app to dev environment
        uses: ./.github/workflows/actions/deploy-ssh-blob-vm
        with:
          environment: "${{ inputs.environment }}"
          storage-account: "${{ vars.AZURE_STORAGE_ACCOUNT }}"
          storage-container: "${{ vars.AZURE_ARTIFACT_CONTAINER }}"
          storage-access-key: "${{ secrets.AZURE_STORAGE_ACCESS_KEY }}"
          ssh-private-key: "${{ secrets.AZURE_VM_SSH_PRIVATE_KEY_DEV }}"
          vm-ip: "${{ secrets.AZURE_VM_IP_DEV }}"
          vm-user: "${{ vars.AZURE_VM_USER }}"
          app-name: "${{ vars.APP_NAME }}"

  deploy-prd:
    name: Deploy to production VMs using ssh and blob
    runs-on: "${{ inputs.runner }}"
    if: ${{ inputs.environment == 'prd' }}
    strategy:
      matrix:
        vm-ips: [prd1, prd2]
    steps:
      - name: Check out the repository    # 리포지토리 체크아웃
        uses: actions/checkout@v4

      - name: Log in to Azure CLI
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          echo "$AZURE_CREDENTIALS" > azure_credentials.json
          az login --service-principal \
            --username $(jq -r .clientId azure_credentials.json) \
            --password $(jq -r .clientSecret azure_credentials.json) \
            --tenant $(jq -r .tenantId azure_credentials.json)
          az account set --subscription $(jq -r .subscriptionId azure_credentials.json)
        shell: bash

      - name: Extract VM IP
        run: echo "TARGET_VM_IP=$(echo '${{ secrets.AZURE_VM_IP_PRD }}' | jq -r .${{ matrix.vm-ips }} )" >> $GITHUB_ENV

      - name: Deploy java app to production
        uses: ./.github/workflows/actions/deploy-ssh-blob-vm
        env:
          TARGET_VM_IP: ${{ env.TARGET_VM_IP }}
        with:
          environment: "${{ inputs.environment }}"
          storage-account: "${{ vars.AZURE_STORAGE_ACCOUNT }}"
          storage-container: "${{ vars.AZURE_ARTIFACT_CONTAINER }}"
          storage-access-key: "${{ secrets.AZURE_STORAGE_ACCESS_KEY }}"
          ssh-private-key: "${{ secrets.AZURE_VM_SSH_PRIVATE_KEY_PRD }}"
          vm-ip: "${{ env.TARGET_VM_IP }}"
          vm-user: "${{ vars.AZURE_VM_USER }}"
          app-name: "${{ vars.APP_NAME }}"