name: Build and Push Docker Image to ACR

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prd
      TagVersion:
        description: 'Tag version for the Docker image'
        required: true
        default: '1.0.0'

env:
  IMAGE_NAME: ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.IMAGE_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK for building the Java project
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    # Build the project using Maven or Gradle
    - name: Build project with Maven
      run: mvn clean package -DskipTests

    # Log in to ACR using Docker login
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ${{ vars.ACR_NAME }}.azurecr.io
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}-${{ github.event.inputs.environment }}:${{ github.event.inputs.TagVersion }}
          ${{ env.IMAGE_NAME }}-${{ github.event.inputs.environment }}:latest
        labels: ${{ steps.meta.outputs.labels }}